# Generated by Django 4.2 on 2025-05-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SoldierApp', '0002_remove_soldier_fee_soldier_discharge_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soldier',
            old_name='discharge_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='soldier',
            old_name='emergency_contact_relation',
            new_name='relation',
        ),
        migrations.RenameField(
            model_name='soldier',
            old_name='enlistment_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='soldier',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
